# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors.

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

## Importing Numpy

In [15]:
# the first step of using numpy is to tell python to use it
import numpy as np

## Cos, sqrt, log

In [23]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


## Numpy Array

In [24]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [25]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


### linspace , Reshape

In [26]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')

#Reshaping
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


## Matrix of 0s, 1s, and identity

In [27]:
#Matrix of zero
mat2 = np.zeros([5,3])
print(mat2)

#Matrix of ones
mat3 = np.ones((3,5))
print('')
print(mat3)

#Identity Matrix
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## arange

In [21]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


## Matrix multiplication

In [22]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


## linalg - solve, inv

In [14]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [15]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


## Rand 

In [34]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.42433616 0.63826512 0.27081522 0.13171666 0.67311621]
 [0.0320257  0.61018882 0.28567525 0.50075779 0.17366139]
 [0.8001132  0.7563492  0.08550452 0.77022358 0.58410806]
 [0.0047388  0.49801243 0.42973793 0.67572263 0.91848267]
 [0.47213685 0.12845897 0.99403237 0.32957296 0.92629123]]

[[-0.7408915   1.32376438  0.39913401  0.38069874  0.34245864]
 [-0.13223875 -1.96511338  0.90026881  0.04122428  0.65262482]
 [ 0.13029539  0.87754495  0.05799537 -1.1319344   0.75587559]
 [ 0.3336071  -0.13081979 -0.21885299 -1.00803078  0.81682611]
 [ 0.0600196   0.45863493 -1.85593412 -0.47185612 -0.16587387]
 [-0.02468073  0.07801798  0.01889054 -1.66755336  0.23069222]
 [ 0.05058253  0.07161233  0.45368547 -0.38579186 -0.72472691]
 [-0.62957526  0.80819105  0.45117329 -0.05228862 -0.16595689]
 [ 0.60834966 -0.63091589 -0.51462362  2.07918785  0.38852459]
 [ 0.83586479 -0.66180107  0.94977376  0.72736757 -0.67600007]]


## Numpy mean, std 

In [35]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4845617488323185
0.771489069180206


## Numpy min, max

In [36]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.004738797423707641
2.0791878540568516


## Accessing Numpy vector

In [37]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.31796872  0.22897466  0.54344347  0.35732199 -0.97846736 -0.14648184
  0.1341322   0.61297157 -1.51846083 -0.0383154   1.02013962 -0.5503544
 -0.08571385 -2.13511123 -0.94657748  1.10110239  1.21196699 -0.01913823
  1.97225432]
0.1341321971704123


In [38]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.97846736 -0.14648184  0.1341322   0.61297157 -1.51846083]


In [39]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.31796872  0.35732199  0.1341322  -0.0383154  -0.08571385]


## Accessing Numpy matrix

In [40]:
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.42433616 0.63826512 0.27081522 0.13171666 0.67311621]
 [0.0320257  0.61018882 0.28567525 0.50075779 0.17366139]
 [0.8001132  0.7563492  0.08550452 0.77022358 0.58410806]
 [0.0047388  0.49801243 0.42973793 0.67572263 0.91848267]
 [0.47213685 0.12845897 0.99403237 0.32957296 0.92629123]]
0.2856752543960841
0.2856752543960841


In [41]:
print(rand_mat[0:2,1:3])

[[0.63826512 0.27081522]
 [0.61018882 0.28567525]]


### Modifying Array

In [42]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-1.31796872  0.22897466  0.54344347  0.35732199 -0.97846736 -0.14648184
  0.1341322   0.61297157 -1.51846083 -0.0383154   1.02013962 -0.5503544
 -0.08571385 -2.13511123 -0.94657748  1.10110239  1.21196699 -0.01913823
  1.97225432]

[-1.31796872  0.22897466  0.54344347  4.          4.         -0.14648184
  0.1341322   0.61297157 -1.51846083 -0.0383154   1.02013962 -0.5503544
 -0.08571385 -2.13511123 -0.94657748  1.10110239  1.21196699 -0.01913823
  1.97225432]

[-1.31796872  0.22897466  0.54344347  1.          2.         -0.14648184
  0.1341322   0.61297157 -1.51846083 -0.0383154   1.02013962 -0.5503544
 -0.08571385 -2.13511123 -0.94657748  1.10110239  1.21196699 -0.01913823
  1.97225432]


In [26]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.16880535 0.35894606 0.28890073 0.4544318  0.40756237]
 [0.0825886  0.64903667 0.81768018 0.09921356 0.05545955]
 [0.10335177 0.34597068 0.46429314 0.61668503 0.81072597]
 [0.13637321 0.02436527 0.99848828 0.83753101 0.30194466]
 [0.4862722  0.180414   0.66620005 0.48111588 0.89633482]]

[[0.16880535 0.35894606 0.28890073 0.4544318  0.40756237]
 [0.0825886  0.64903667 0.81768018 0.         0.        ]
 [0.10335177 0.34597068 0.46429314 0.         0.        ]
 [0.13637321 0.02436527 0.99848828 0.83753101 0.30194466]
 [0.4862722  0.180414   0.66620005 0.48111588 0.89633482]]


In [27]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.16880535 0.35894606 0.28890073]
 [0.0825886  0.64903667 0.81768018]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [28]:
print(rand_mat)

[[3.         3.         3.         0.4544318  0.40756237]
 [3.         3.         3.         0.         0.        ]
 [0.10335177 0.34597068 0.46429314 0.         0.        ]
 [0.13637321 0.02436527 0.99848828 0.83753101 0.30194466]
 [0.4862722  0.180414   0.66620005 0.48111588 0.89633482]]


## Creating copy of matrix

In [43]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[0.42433616 0.63826512 0.27081522 0.13171666 0.67311621]
 [0.0320257  0.61018882 0.28567525 0.50075779 0.17366139]
 [0.8001132  0.7563492  0.08550452 0.77022358 0.58410806]
 [0.0047388  0.49801243 0.42973793 0.67572263 0.91848267]
 [0.47213685 0.12845897 0.99403237 0.32957296 0.92629123]]


## Accessing entries using logical conditions 

In [45]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.92244713  0.07899947 -0.14682032  1.10980064  0.02125642 -0.92320121
 -0.85235685  0.79584656 -0.75772006  0.87321983 -0.63056231 -2.01555767
  1.44572475 -0.34915105 -0.83880854]
[ True  True False  True  True False False  True False  True False False
  True False False]
[0.92244713 0.07899947 1.10980064 0.02125642 0.79584656 0.87321983
 1.44572475]


In [46]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.7408915   1.32376438  0.39913401  0.38069874  0.34245864]
 [-0.13223875 -1.96511338  0.90026881  0.04122428  0.65262482]
 [ 0.13029539  0.87754495  0.05799537 -1.1319344   0.75587559]
 [ 0.3336071  -0.13081979 -0.21885299 -1.00803078  0.81682611]
 [ 0.0600196   0.45863493 -1.85593412 -0.47185612 -0.16587387]
 [-0.02468073  0.07801798  0.01889054 -1.66755336  0.23069222]
 [ 0.05058253  0.07161233  0.45368547 -0.38579186 -0.72472691]
 [-0.62957526  0.80819105  0.45117329 -0.05228862 -0.16595689]
 [ 0.60834966 -0.63091589 -0.51462362  2.07918785  0.38852459]
 [ 0.83586479 -0.66180107  0.94977376  0.72736757 -0.67600007]]
[1.32376438 0.39913401 0.38069874 0.34245864 0.90026881 0.04122428
 0.65262482 0.13029539 0.87754495 0.05799537 0.75587559 0.3336071
 0.81682611 0.0600196  0.45863493 0.07801798 0.01889054 0.23069222
 0.05058253 0.07161233 0.45368547 0.80819105 0.45117329 0.60834966
 2.07918785 0.38852459 0.83586479 0.94977376 0.72736757]


In [47]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.92244713  0.07899947 -0.14682032  1.10980064  0.02125642 -0.92320121
 -0.85235685  0.79584656 -0.75772006  0.87321983 -0.63056231 -2.01555767
  1.44572475 -0.34915105 -0.83880854]

[-5.          0.07899947 -0.14682032 -5.          0.02125642 -0.92320121
 -0.85235685 -5.         -0.75772006 -5.         -0.63056231 -2.01555767
 -5.         -0.34915105 -0.83880854]


## Saving on disk

In [49]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [50]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

## Loding from disk

In [53]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.7408915   1.32376438  0.39913401  0.38069874  0.34245864]
 [-0.13223875 -1.96511338  0.90026881  0.04122428  0.65262482]
 [ 0.13029539  0.87754495  0.05799537 -1.1319344   0.75587559]
 [ 0.3336071  -0.13081979 -0.21885299 -1.00803078  0.81682611]
 [ 0.0600196   0.45863493 -1.85593412 -0.47185612 -0.16587387]
 [-0.02468073  0.07801798  0.01889054 -1.66755336  0.23069222]
 [ 0.05058253  0.07161233  0.45368547 -0.38579186 -0.72472691]
 [-0.62957526  0.80819105  0.45117329 -0.05228862 -0.16595689]
 [ 0.60834966 -0.63091589 -0.51462362  2.07918785  0.38852459]
 [ 0.83586479 -0.66180107  0.94977376  0.72736757 -0.67600007]]



In [54]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[0.42433616 0.63826512 0.27081522 0.13171666 0.67311621]
 [0.0320257  0.61018882 0.28567525 0.50075779 0.17366139]
 [0.8001132  0.7563492  0.08550452 0.77022358 0.58410806]
 [0.0047388  0.49801243 0.42973793 0.67572263 0.91848267]
 [0.47213685 0.12845897 0.99403237 0.32957296 0.92629123]]

[[-0.7408915   1.32376438  0.39913401  0.38069874  0.34245864]
 [-0.13223875 -1.96511338  0.90026881  0.04122428  0.65262482]
 [ 0.13029539  0.87754495  0.05799537 -1.1319344   0.75587559]
 [ 0.3336071  -0.13081979 -0.21885299 -1.00803078  0.81682611]
 [ 0.0600196   0.45863493 -1.85593412 -0.47185612 -0.16587387]
 [-0.02468073  0.07801798  0.01889054 -1.66755336  0.23069222]
 [ 0.05058253  0.07161233  0.45368547 -0.38579186 -0.72472691]
 [-0.62957526  0.80819105  0.45117329 -0.05228862 -0.16595689]
 [ 0.60834966 -0.63091589 -0.51462362  2.07918785  0.38852459]
 [ 0.83586479 -0.66180107  0.94977376  0.72736757 -0.67600007]]
[[0.42433616 0.63826512 0.27081522 0.13171666 0.67311621]
 [0.0320257  0.6101

In [55]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[0.42433616 0.63826512 0.27081522 0.13171666 0.67311621]
 [0.0320257  0.61018882 0.28567525 0.50075779 0.17366139]
 [0.8001132  0.7563492  0.08550452 0.77022358 0.58410806]
 [0.0047388  0.49801243 0.42973793 0.67572263 0.91848267]
 [0.47213685 0.12845897 0.99403237 0.32957296 0.92629123]]

[[0.42433616 0.63826512 0.27081522 0.13171666 0.67311621]
 [0.0320257  0.61018882 0.28567525 0.50075779 0.17366139]
 [0.8001132  0.7563492  0.08550452 0.77022358 0.58410806]
 [0.0047388  0.49801243 0.42973793 0.67572263 0.91848267]
 [0.47213685 0.12845897 0.99403237 0.32957296 0.92629123]]
